# Generated by Django 4.1.7 on 2023-03-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250, verbose_name='Название')),
                ('Author', models.CharField(max_length=100, verbose_name='Автор')),
                ('Description', models.TextField(max_length=10000, verbose_name='Описание')),
                ('Price', models.IntegerField(verbose_name='Цена')),
                ('Remainder', models.IntegerField(verbose_name='В наличии')),
                ('Image', models.CharField(max_length=1000, verbose_name='Картинка')),
                ('NumberOfPages', models.IntegerField(verbose_name='Количество страниц')),
                ('SourceName', models.CharField(max_length=1000, verbose_name='Ссылка')),
                ('Genre', models.CharField(max_length=100, verbose_name='Жанр')),
            ],
        ),
    ]
