# Generated by Django 4.1.7 on 2023-02-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('date', models.IntegerField(verbose_name='Год')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('count_of_pages', models.IntegerField(verbose_name='Количество страниц')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('in_stock', models.IntegerField(verbose_name='В наличии')),
                ('review', models.TextField(max_length=10000, verbose_name='Описание')),
            ],
        ),
    ]
